output "Bastion-ansible_public_addresses" {
    value = aws_instance.Bastion-ansible[0].public_ip
}
output "Jenkins-Master-public_addresses" {
    value = aws_instance.jenkins_server[0].public_ip
}
output "consul_servers_1" {
  value = aws_instance.consul-Server[2].private_ip
}
output "consul_servers_2" {
  value = aws_instance.consul-Server[1].private_ip
}
output "consul_servers_3" {
  value = aws_instance.consul-Server[0].private_ip
}
output "consul_agent_ips" {
  value = aws_instance.consul-agent[*].private_ip
}
#output "consul_servers_ids-1" {
#  value = aws_instance.consul-Server[2].id
#}
#output "consul_servers_ids-2" {
#  value = aws_instance.consul-Server[1].id
#}
#output "consul_servers_ids-3" {
#  value = aws_instance.consul-Server[0].id
#}
#output "consul_servers_ids-agent" {
#  value = aws_instance.consul-agent[0].id
#}
#output  "consul_server" {
#  value = aws_instance.consul
#}
#output "common_sg_id" {
#  value = aws_security_group.common.id
#}
output "lb_consul_dns" {
  value = aws_lb.consul_lb[*].dns_name
}

#output for k8s cluster

output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

# output "kubectl_config" {
#   description = "kubectl config as generated by the module."
#   value       = module.eks.kubeconfig
# }

output "region" {
  description = "AWS region"
  value       = var.aws_region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = var.cluster_name
}

output "oidc_provider_arn" {
  value = module.eks.oidc_provider_arn
}