route:
  receiver: 'discord_webhook'
  repeat_interval: 4h
  group_by: [alertname]

receivers:
- name: 'discord_webhook'
  webhook_configs:
    - url: 'https://discordapp.com/api/webhooks/1003615908998156369/zGQrSwpypO4StPGfnBPPL-8IVNgap8XaDQ9pwgZEjAF6YHABl8aeTCmxJOvUkG1CTxuP:9093'


