---
- name: configure consul 
  hosts:  consul-server
  become: true
  
  vars:
    allow_world_readable_tmpfiles: true
     
  roles:
  - consul-server


- hosts: consul-server
  become: true
  tasks:
  - name: restart consul cluster
    service:
      name: consul.service
      state: restarted